
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Live-Updates für backend-Code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Live-Updates für Frontend-Code
      - /app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - mynetwork
    command: npm start
networks:
  mynetwork: