
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Live-Updates für backend-Code
      - ./shared_data:/shared_data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Live-Updates für Frontend-Code
      - /app/node_modules
      - ./shared_data:/shared_data
    depends_on:
      - backend
    command: npm start
